### ISSUE TITLE
[BUG] - Links missing in left navigation

### ISSUE THREAD

**Issue by jaas666** [nhcarrigan/notes#92]
### What bug did you encounter?

If you click the [General Notes](https://www.nhcarrigan.com/notes/#/general/index) link the page shows more "notes" than linked on the navigation on the left.

### What did you expect to happen?

Links to all "notes" included on the navigation on the left.

### Screenshots

![Screenshot_20220420-111519_Chrome](https://user-images.githubusercontent.com/30204147/164276236-0d72bd9b-7a22-4379-bb7b-e995ca030437.png)

**Comment by nhcarrigan** [comment]
## Good First Issue

Thank you for reporting this issue. This looks something that can be fixed by first time contributors to this repository. If you have already made a contribution to this project, please reserve this issue for a new contributor.

Here are the steps to resolve this issue:

- Within the [general notes index file](https://github.com/nhcarrigan/notes/blob/main/docs/general/index.md):
  - Remove the DigitalOcean Droplet Setup section.
  - Remove the LetsEncrypt section.

Please make sure you read [our guidelines for contributing](../blob/main/CONTRIBUTING.md). If you have any questions about how to resolve this issue, or about the contributing process in general, [join us in our chat room](http://chat.nhcarrigan.com).

If you are interested in addressing this issue, reply here and we can assign the issue to you. If someone is already assigned to the issue, please allow them time to submit a pull request before requesting to be assigned yourself. Issues are typically unassigned after a week of inactivity.
